# https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc
version: '3'

services:
    app:
        image: dorowu/ubuntu-desktop-lxde-vnc
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "${PORT}:80"
            - "${VNC_PORT}:5900"
        restart: unless-stopped
        environment:
            - VNC_PASSWORD=${VNC_PASSWORD}
            - USER=${USER}
            - PASSWORD=${PASSWORD}